import type { AppRole, DashboardAppointment, DashboardParticipant, DashboardRepository, DashboardTrajectory } from '../domain';

const trajectories: DashboardTrajectory[]=[
 {code:'MW-RSD-001',name:'Munks Werkt Zeist',commissionerName:'Regionale Sociale Dienst Kromme Rijn Heuvelrug',startDate:'01-09-2026',endDate:'20-10-2026',status:'active',coaches:[{id:'c1',name:'Eva Jansen'},{id:'c2',name:'Mohammed El Idrissi'}],participants:[
  {id:'p1',name:'Sam de Jong',email:'sam.dejong@voorbeeld.nl',phone:'06 12345678',coachId:'c1',appSteps:[true,true,true,false,false,false,false],attendance:[true,true,null,true,null,false,false],needsAttention:false,completed:false,goals:'Deels',startScores:[5,6,6,4,5],documents:[{type:'cv',fileName:'CV Sam de Jong.pdf',uploadedAt:'12-09-2026'}],appAnswers:[{step:1,title:'Waar sta je nu?',answers:[{question:'Wat wil je tijdens dit traject bereiken?',answer:'Ik wil ontdekken welk werk bij mij past en meer vertrouwen krijgen.'},{question:'Waar heb je nu vooral hulp bij nodig?',answer:'Bij het kiezen van passend werk en het maken van mijn cv.'}]},{step:3,title:'Mijn cv',answers:[{question:'Waar ben je goed in?',answer:'Ik werk nauwkeurig, ben behulpzaam en kan goed samenwerken.'},{question:'Waar krijg je energie van?',answer:'Van praktisch werk en contact met mensen.'}]}]},
  {id:'p2',name:'Noor Bakker',email:'noor.bakker@voorbeeld.nl',phone:'06 23456789',coachId:'c1',appSteps:[true,true,true,true,true,false,false],attendance:[true,true,null,true,null,true,false],needsAttention:true,completed:false,goals:'Deels',startScores:[4,5,7,4,4],documents:[{type:'cv',fileName:'CV Noor Bakker.pdf',uploadedAt:'13-09-2026'}],appAnswers:[{step:1,title:'Waar sta je nu?',answers:[{question:'Wat wil je tijdens dit traject bereiken?',answer:'Ik wil een opleiding of baan vinden waarin ik met mensen werk.'}]},{step:5,title:'Werk of opleiding zoeken',answers:[{question:'Wat past bij jou?',answer:'Opleidingen bekijken en vacatures zoeken.'},{question:'Wat vind je belangrijk in werk?',answer:'Duidelijke werktijden, contact met mensen en ruimte om te leren.'}]}]},
  {id:'p3',name:'Yassin El Amrani',email:'yassin.elamrani@voorbeeld.nl',phone:'06 34567890',coachId:'c2',appSteps:[true,true,false,false,false,false,false],attendance:[true,false,null,false,null,false,false],needsAttention:true,completed:false,goals:'Nee',startScores:[3,4,4,3,4]}
 ]},
 {code:'MW-RSD-002',name:'Munks Werkt Amersfoort',commissionerName:'Regionale Sociale Dienst Kromme Rijn Heuvelrug',startDate:'15-09-2026',endDate:'03-11-2026',status:'active',coaches:[{id:'c2',name:'Mohammed El Idrissi'},{id:'c3',name:'Sanne Vos'}],participants:[
  {id:'p4',name:'Sophie de Wit',email:'sophie.dewit@voorbeeld.nl',phone:'06 45678901',coachId:'c3',appSteps:[true,true,true,true,true,true,true],attendance:[true,true,null,true,null,true,true],needsAttention:false,completed:true,goals:'Ja',outcomeCategory:'Werk en opleiding',outcomeSummary:'Start met een BBL-traject in de verkoop.',outcomeStatus:'final',startScores:[4,5,6,4,5],endScores:[8,8,8,7,8]},
  {id:'p5',name:'Daniël Smit',email:'daniel.smit@voorbeeld.nl',phone:'06 56789012',coachId:'c2',appSteps:[true,true,true,true,false,false,false],attendance:[true,true,null,true,null,false,false],needsAttention:false,completed:false,goals:'Deels',startScores:[5,5,5,5,5]}
 ]}
];

export class DemoDashboardRepository implements DashboardRepository {
 private appointments:DashboardAppointment[]=[];
 async listAppointments(trajectoryCode:string){return this.appointments.filter(item=>item.trajectoryCode===trajectoryCode)}
 async saveAppointment(appointment:Omit<DashboardAppointment,'coachName'|'cancelled'>){const coachName=trajectories.find(item=>item.code===appointment.trajectoryCode)?.coaches.find(coach=>coach.id===appointment.coachId)?.name??'';const item={...appointment,coachName,cancelled:false};const index=this.appointments.findIndex(existing=>existing.id===appointment.id);if(index>=0)this.appointments[index]={...item,cancelled:this.appointments[index].cancelled};else this.appointments.push({...item,id:appointment.id||`a${Date.now()}`})}
 async setAppointmentActive(appointmentId:string,active:boolean){const item=this.appointments.find(appointment=>appointment.id===appointmentId);if(item)item.cancelled=!active}
 async saveManagedUser(){return}
 async saveCommissioner(){return}
 async listManagementOptions(){return {coaches:[{id:'c1',name:'Eva Jansen'},{id:'c2',name:'Mohammed El Idrissi'},{id:'c3',name:'Sanne Vos'}],commissioners:[{code:'RSDZEIST',name:'Regionale Sociale Dienst Kromme Rijn Heuvelrug'}]}}
 async listTrajectories(_role:Exclude<AppRole,'participant'>){return structuredClone(trajectories)}
 async updateAttendance(trajectoryCode:string,participantId:string,stepIndex:number,present:boolean){const participant=trajectories.find(t=>t.code===trajectoryCode)?.participants.find(p=>p.id===participantId);if(!participant||participant.attendance[stepIndex]===null)throw new Error('Aanwezigheid kan voor deze stap niet worden gewijzigd.');participant.attendance[stepIndex]=present}
 async releaseOutcome(trajectoryCode:string,participantId:string,category:string,summary:string,status:'provisional'|'final',goals:DashboardParticipant['goals']){const participant=trajectories.find(t=>t.code===trajectoryCode)?.participants.find(p=>p.id===participantId);if(!participant)throw new Error('Deelnemer niet gevonden.');participant.outcomeCategory=category;participant.outcomeSummary=summary;participant.outcomeStatus=status;participant.goals=goals;if(status==='final')participant.completed=true}
 async createTrajectory(input:Pick<DashboardTrajectory,'code'|'name'|'commissionerName'|'startDate'|'endDate'|'coaches'>){if(trajectories.some(t=>t.code===input.code))throw new Error('Deze trajectcode bestaat al.');trajectories.push({...input,status:'planned',participants:[]})}
 async updateTrajectory(code:string,input:Pick<DashboardTrajectory,'name'|'commissionerName'|'startDate'|'endDate'|'coaches'>){const trajectory=trajectories.find(t=>t.code===code);if(!trajectory)throw new Error('Traject niet gevonden.');Object.assign(trajectory,input)}
 async addParticipant(trajectoryCode:string,input:Pick<DashboardParticipant,'name'|'email'|'phone'|'city'|'birthDate'|'coachId'>){const trajectory=trajectories.find(t=>t.code===trajectoryCode);if(!trajectory)throw new Error('Traject niet gevonden.');if(!trajectory.coaches.some(coach=>coach.id===input.coachId))throw new Error('Selecteer een begeleider die aan dit traject is gekoppeld.');trajectory.participants.push({id:`p${Date.now()}`,...input,appSteps:[false,false,false,false,false,false,false],attendance:[false,false,null,false,null,false,false],needsAttention:false,completed:false,goals:'Nog niet bekend'});return {activationCode:'482913'}}
 async updateParticipant(trajectoryCode:string,participantId:string,input:Pick<DashboardParticipant,'name'|'email'|'phone'|'city'|'birthDate'|'coachId'>){const trajectory=trajectories.find(t=>t.code===trajectoryCode);if(!trajectory)throw new Error('Traject niet gevonden.');if(!trajectory.coaches.some(coach=>coach.id===input.coachId))throw new Error('Selecteer een begeleider die aan dit traject is gekoppeld.');const participant=trajectory.participants.find(item=>item.id===participantId);if(!participant)throw new Error('Deelnemer niet gevonden.');Object.assign(participant,input)}
 async renewParticipantActivation(){return {activationCode:'482913'}}
 async uploadParticipantDocument(trajectoryCode:string,participantId:string,type:'cv'|'talent_report',file:File){const participant=trajectories.find(t=>t.code===trajectoryCode)?.participants.find(p=>p.id===participantId);if(!participant)throw new Error('Deelnemer niet gevonden.');participant.documents=(participant.documents||[]).filter(document=>document.type!==type);participant.documents.push({type,fileName:file.name,uploadedAt:new Date().toLocaleDateString('nl-NL',{day:'2-digit',month:'2-digit',year:'numeric'}).replaceAll('/','-')})}
 async openParticipantDocument(){throw new Error('Dit demonstratiedocument bevat geen echt bestand.')}
 async releaseTalentResults(trajectoryCode:string,participantId:string){const participant=trajectories.find(t=>t.code===trajectoryCode)?.participants.find(p=>p.id===participantId);if(!participant)throw new Error('Deelnemer niet gevonden.');participant.talentStatus='released'}
}
