import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { AiMessage, SupabaseAiRepository } from './repositories/supabaseAiRepository';
import { formatDateTime } from './formatDateTime';

function MessageText({body}:{body:string}){
 const blocks:Array<{type:'p'|'ul'|'ol';items:string[]}>=[];let paragraph:string[]=[];
 const flushParagraph=()=>{if(paragraph.length){blocks.push({type:'p',items:[paragraph.join(' ')]});paragraph=[]}};
 for(const rawLine of body.split('\n')){const line=rawLine.trim();if(!line){flushParagraph();continue}const numbered=line.match(/^\d+[.)]\s+(.+)$/),bullet=line.match(/^[-•]\s+(.+)$/);if(numbered||bullet){flushParagraph();const type=numbered?'ol':'ul',item=(numbered||bullet)![1];const previous=blocks.at(-1);if(previous?.type===type)previous.items.push(item);else blocks.push({type,items:[item]})}else paragraph.push(line)}
 flushParagraph();
 return <div className="ai-message-text">{blocks.map((block,index)=>block.type==='p'?<p key={index}>{block.items[0]}</p>:block.type==='ol'?<ol key={index}>{block.items.map((item,itemIndex)=><li key={itemIndex}>{item}</li>)}</ol>:<ul key={index}>{block.items.map((item,itemIndex)=><li key={itemIndex}>{item}</li>)}</ul>)}</div>
}

export function AiAssistant({repository,onClose,initialQuestion=''}:{repository:SupabaseAiRepository;onClose:()=>void;initialQuestion?:string}){
 const[messages,setMessages]=useState<AiMessage[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[enabled,setEnabled]=useState<boolean>();
 const questionRef=useRef<HTMLTextAreaElement>(null),formRef=useRef<HTMLFormElement>(null),hasPositionedRef=useRef(false);
 useEffect(()=>{repository.status().then(value=>{setEnabled(value);if(value)return repository.list().then(setMessages)}).catch(reason=>setError(reason instanceof Error?reason.message:'Laden is niet gelukt.'))},[repository]);
 useEffect(()=>{if(enabled!==true||hasPositionedRef.current)return;hasPositionedRef.current=true;requestAnimationFrame(()=>{formRef.current?.scrollIntoView({block:'end'});if(initialQuestion)questionRef.current?.focus({preventScroll:true})})},[enabled,initialQuestion]);
 useEffect(()=>{if(hasPositionedRef.current&&messages.length)requestAnimationFrame(()=>formRef.current?.scrollIntoView({block:'end'}))},[messages]);
 const changeConsent=async(value:boolean)=>{setBusy(true);setError('');try{setEnabled(await repository.setEnabled(value));if(value)setMessages(await repository.list())}catch(reason){setError(reason instanceof Error?reason.message:'De keuze kon niet worden opgeslagen.')}finally{setBusy(false)}};
 const send=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,text=String(new FormData(form).get('message')||'').trim();if(!text||busy)return;setError('');setBusy(true);repository.send(text).then(()=>{form.reset();return repository.list()}).then(setMessages).catch(reason=>setError(reason instanceof Error?reason.message:'Versturen is niet gelukt.')).finally(()=>setBusy(false))};
 if(enabled===undefined&&!error)return <section className="screen ai-screen"><button className="message-back" onClick={onClose}>← Terug</button><p>AI-assistent laden…</p></section>;
 if(enabled===false)return <section className="screen ai-screen"><button className="message-back" onClick={onClose}>← Terug</button><span className="eyebrow">Jouw keuze</span><h1>AI-assistent</h1><p>De AI-assistent staat voor jouw account uit. Gebruik is vrijwillig en heeft geen gevolgen voor je traject.</p><div className="ai-disclaimer">De assistent kan helpen met werk, opleiding, cv en gesprekken. Deel geen BSN, wachtwoord of identiteitsbewijs.</div><button className="flow-primary" disabled={busy} onClick={()=>void changeConsent(true)}>AI-assistent aanzetten</button>{error&&<p className="auth-error">{error}</p>}</section>;
 return <section className="screen ai-screen"><button className="message-back" onClick={onClose}>← Terug</button><span className="eyebrow">Persoonlijke hulp</span><h1>AI-assistent</h1><p>Vraag hulp bij werk, opleiding, je cv of een gesprek. Deel geen BSN, wachtwoord of identiteitsbewijs.</p><div className="ai-disclaimer">De AI-assistent kan fouten maken en neemt geen beslissingen over jouw traject. Bespreek belangrijke keuzes met je begeleider.</div><button className="auth-secondary" disabled={busy} onClick={()=>void changeConsent(false)}>AI-assistent uitzetten</button><div className="ai-thread">{messages.map(message=><article className={message.sender} key={message.id}><strong>{message.sender==='participant'?'Jij':'AI-assistent'}</strong><MessageText body={message.body}/><small>{formatDateTime(message.sentAt)}</small></article>)}{!messages.length&&!error&&<p className="notice-box">Stel bijvoorbeeld een vraag over je cv, een opleiding of de voorbereiding van een sollicitatiegesprek.</p>}</div><form ref={formRef} className="ai-form" onSubmit={send}><label>Jouw vraag<textarea ref={questionRef} name="message" required maxLength={1500} defaultValue={initialQuestion} placeholder="Waarmee kan ik je helpen?"/></label><button className="flow-primary" disabled={busy}>{busy?'Even nadenken…':'Verstuur vraag'}</button></form>{error&&<p className="auth-error" role="alert">{error}</p>}</section>
}
