import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import type { DashboardAppointment, DashboardRepository, DashboardTrajectory } from './domain';

const toIsoDate=(value:string)=>{const match=/^(\d{2})-(\d{2})-(\d{4})$/.exec(value);return match?`${match[3]}-${match[2]}-${match[1]}`:''};
const toDutchDate=(value:string)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return match?`${match[3]}-${match[2]}-${match[1]}`:value};

export function AppointmentsAdmin({trajectory,repository}:{trajectory:DashboardTrajectory;repository:DashboardRepository}){
 const[items,setItems]=useState<DashboardAppointment[]>([]),[editing,setEditing]=useState<DashboardAppointment>(),[creating,setCreating]=useState(false),[showCancelled,setShowCancelled]=useState(false),[message,setMessage]=useState('');
 const load=()=>repository.listAppointments(trajectory.code).then(appointments=>setItems(appointments.sort((left,right)=>left.stepNumber-right.stepNumber||left.date.localeCompare(right.date)||left.startTime.localeCompare(right.startTime)))).catch(error=>setMessage(error instanceof Error?error.message:'Afspraken laden is mislukt.'));
 useEffect(()=>{void load();setCreating(false);setEditing(undefined)},[repository,trajectory.code]);
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const stepNumber=Number(data.get('step'));try{await repository.saveAppointment({id:editing?.id??'',trajectoryCode:trajectory.code,stepNumber,title:String(data.get('title')||'').trim(),date:String(data.get('date')||''),startTime:String(data.get('startTime')||''),endTime:String(data.get('endTime')||''),location:String(data.get('location')||'').trim(),explanation:String(data.get('explanation')||'').trim(),coachId:String(data.get('coachId')||''),participantId:stepNumber===2||stepNumber===7?String(data.get('participantId')||''):undefined});await load();setCreating(false);setEditing(undefined);setMessage('De afspraak is opgeslagen en zichtbaar voor de deelnemers.')}catch(error){setMessage(error instanceof Error?error.message:'Opslaan is mislukt.')}};
 const toggleActive=async(item:DashboardAppointment)=>{if(!item.cancelled&&!window.confirm(`Wil je de afspraak “${item.title}” annuleren? De afspraak verdwijnt dan bij de deelnemers.`))return;try{await repository.setAppointmentActive(item.id,item.cancelled);await load();setMessage(item.cancelled?'De afspraak is opnieuw geactiveerd.':'De afspraak is geannuleerd.')}catch(error){setMessage(error instanceof Error?error.message:'De afspraakstatus kon niet worden gewijzigd.')}};
 if(creating||editing)return <section className="admin-form"><h2>{editing?'Afspraak wijzigen':'Nieuwe afspraak'}</h2>{message&&<p className="dashboard-message">{message}</p>}<form onSubmit={save}><label>Trajectstap<select name="step" required defaultValue={editing?.stepNumber??1}>{Array.from({length:7},(_,index)=><option value={index+1} key={index+1}>Stap {index+1}</option>)}</select></label><label>Deelnemer <small>Vul dit in voor een individueel gesprek bij stap 2 of 7.</small><select name="participantId" defaultValue={editing?.participantId??''}><option value="">Groepsafspraak</option>{trajectory.participants.map(participant=><option value={participant.id} key={participant.id}>{participant.name}</option>)}</select></label><label>Titel<input name="title" required defaultValue={editing?.title??''}/></label><label>Datum<input name="date" type="date" min={toIsoDate(trajectory.startDate)} max={toIsoDate(trajectory.endDate)} required defaultValue={editing?.date??''}/><small>Kies een datum van {trajectory.startDate} tot en met {trajectory.endDate}.</small></label><label>Begintijd<input name="startTime" type="time" required defaultValue={editing?.startTime??''}/></label><label>Eindtijd<input name="endTime" type="time" required defaultValue={editing?.endTime??''}/></label><label>Locatie<input name="location" defaultValue={editing?.location??''}/></label><label>Begeleider<select name="coachId" required defaultValue={editing?.coachId??''}><option value="" disabled>Selecteer een begeleider</option>{trajectory.coaches.map(coach=><option value={coach.id} key={coach.id}>{coach.name}</option>)}</select></label><label>Toelichting<textarea name="explanation" defaultValue={editing?.explanation??''}/></label><div><button className="release-button">Opslaan</button><button type="button" className="close-button" onClick={()=>{setCreating(false);setEditing(undefined)}}>Annuleren</button></div></form></section>;
 const visibleItems=items.filter(item=>showCancelled||!item.cancelled);
 const needsReassignment=(item:DashboardAppointment)=>!item.cancelled&&item.date>=new Date().toLocaleDateString('sv-SE')&&!trajectory.coaches.some(coach=>coach.id===item.coachId);
 const reassignmentCount=items.filter(needsReassignment).length;
 return <section className="admin-panel">
  <header><div><h2>Afsprakenkalender</h2><p>Plan de groepsbijeenkomsten bij de zeven trajectstappen.</p></div><button onClick={()=>{setCreating(true);setEditing(undefined);setMessage('')}}>Nieuwe afspraak</button></header>
  {message&&<p className="dashboard-message">{message}</p>}
  {reassignmentCount>0&&<p className="dashboard-message" role="alert">{reassignmentCount} toekomstige {reassignmentCount===1?'afspraak heeft':'afspraken hebben'} een inactieve of niet meer gekoppelde begeleider. Kies bij Wijzigen een actieve begeleider.</p>}
  <label className="check"><input type="checkbox" checked={showCancelled} onChange={event=>setShowCancelled(event.target.checked)}/><span>Toon ook geannuleerde afspraken</span></label>
  <div className="admin-trajectories appointment-list">{visibleItems.length?visibleItems.map(item=><article className={item.cancelled?'cancelled-appointment':''} key={item.id}>
   <div className="appointment-details"><strong>Stap {item.stepNumber} · {item.title}{item.cancelled?' · Geannuleerd':''}</strong><span><b>Datum</b>{toDutchDate(item.date)}</span><span><b>Tijd</b>{item.startTime}–{item.endTime}</span><span><b>Locatie</b>{item.location||'Nog niet ingevuld'}</span><span><b>Begeleider</b>{item.coachName}</span>{needsReassignment(item)&&<p className="appointment-reassignment" role="alert">Begeleider niet beschikbaar · kies een andere begeleider</p>}{item.participantName&&<span><b>Deelnemer</b>{item.participantName}</span>}</div>
   <div><button onClick={()=>{setEditing(item);setCreating(false);setMessage('')}}>Wijzigen</button><button type="button" onClick={()=>void toggleActive(item)}>{item.cancelled?'Opnieuw activeren':'Annuleren'}</button></div>
  </article>):<p>{items.length?'Er zijn geen actieve afspraken voor dit traject.':'Nog geen afspraken gepland voor dit traject.'}</p>}</div>
 </section>;
}
