import { useEffect, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import type { DashboardCoach, DashboardRepository, DashboardTrajectory } from './domain';

const toIsoDate=(value?:string)=>{const match=/^(\d{2})-(\d{2})-(\d{4})$/.exec(value??'');return match?`${match[3]}-${match[2]}-${match[1]}`:''};
const toDutchDate=(value:string)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return match?`${match[3]}-${match[2]}-${match[1]}`:value};

export function DashboardAdmin({repository,trajectories,selected,onSelected,onChanged}:{repository:DashboardRepository;trajectories:DashboardTrajectory[];selected:string;onSelected:(code:string)=>void;onChanged:()=>Promise<void>}){
 const[showInactiveParticipants,setShowInactiveParticipants]=useState(false);
 const[renewBusy,setRenewBusy]=useState(false);
 const[createdParticipant,setCreatedParticipant]=useState<{name:string;activationCode:string}|null>(null);
 const[mode,setMode]=useState<'list'|'new-trajectory'|'edit-trajectory'|'new-participant'|'participant-created'|'edit-participant'>('list');const[message,setMessage]=useState('');const[selectedParticipantId,setSelectedParticipantId]=useState('');const[availableCoaches,setAvailableCoaches]=useState<DashboardCoach[]>([]);const[commissioners,setCommissioners]=useState<Array<{code:string;name:string}>>([]);const[selectedCommissionerCode,setSelectedCommissionerCode]=useState('');useEffect(()=>{repository.listManagementOptions().then(options=>{setAvailableCoaches(options.coaches);setCommissioners(options.commissioners);setSelectedCommissionerCode(current=>current||options.commissioners[0]?.code||'')}).catch(error=>setMessage(error instanceof Error?error.message:'Beheeropties laden is niet gelukt.'))},[repository]);const trajectory=trajectories.find(t=>t.code===selected);const selectedParticipant=trajectory?.participants.find(item=>item.id===selectedParticipantId);const codePrefix=`MW-${selectedCommissionerCode}-`;const nextNumber=Math.max(0,...trajectories.filter(item=>item.code.startsWith(codePrefix)).map(item=>Number(item.code.slice(codePrefix.length))||0))+1;const generatedCode=`${codePrefix}${String(nextNumber).padStart(3,'0')}`;
 const fields=(form:HTMLFormElement)=>{const data=new FormData(form);return {name:String(data.get('name')||'').trim(),commissionerName:String(data.get('commissioner')||'').trim(),startDate:toDutchDate(String(data.get('start')||'').trim()),endDate:toDutchDate(String(data.get('end')||'').trim()),coaches:availableCoaches.filter(coach=>data.getAll('coaches').includes(coach.id))}};
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();try{await repository.createTrajectory({code:generatedCode,...fields(event.currentTarget)});await onChanged();setMode('list');setMessage(`Het traject is toegevoegd met code ${generatedCode}.`)}catch(error){setMessage(error instanceof Error?error.message:'Toevoegen is niet gelukt.')}};
 const edit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!trajectory)return;try{await repository.updateTrajectory(trajectory.code,fields(event.currentTarget));await onChanged();setMode('list');setMessage('De trajectgegevens zijn bijgewerkt.')}catch(error){setMessage(error instanceof Error?error.message:'Wijzigen is niet gelukt.')}};
 const add=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!trajectory)return;const data=new FormData(event.currentTarget);const participantName=String(data.get('name')||'').trim();try{const result=await repository.addParticipant(trajectory.code,{name:participantName,email:String(data.get('email')||'').trim(),phone:String(data.get('phone')||'').trim(),city:String(data.get('city')||'').trim(),birthDate:String(data.get('birthDate')||''),coachId:String(data.get('coachId')||'')});if(!result?.activationCode)throw new Error('De deelnemer is toegevoegd, maar de activatiecode ontbreekt. Maak een nieuwe code bij Deelnemer wijzigen.');setCreatedParticipant({name:participantName,activationCode:result.activationCode});setMessage('');setMode('participant-created');try{await onChanged()}catch{setMessage('De deelnemer is toegevoegd, maar het trajectoverzicht kon niet worden vernieuwd. Bewaar de activatiecode hieronder.')}}catch(error){setMessage(error instanceof Error?error.message:'Toevoegen is niet gelukt.')}};
 const updateParticipant=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!trajectory||!selectedParticipant)return;const data=new FormData(event.currentTarget);try{await repository.updateParticipant(trajectory.code,selectedParticipant.id,{name:String(data.get('name')||'').trim(),email:String(data.get('email')||'').trim(),phone:String(data.get('phone')||'').trim(),city:String(data.get('city')||'').trim(),birthDate:String(data.get('birthDate')||''),coachId:String(data.get('coachId')||''),active:data.get('active')==='on'});await onChanged();setMode('list');setMessage('De deelnemergegevens zijn bijgewerkt.')}catch(error){setMessage(error instanceof Error?error.message:'Wijzigen is niet gelukt.')}};
 const renew=async()=>{if(!trajectory||!selectedParticipant||renewBusy)return;setMessage('');setRenewBusy(true);try{const result=await repository.renewParticipantActivation(trajectory.code,selectedParticipant.id);setMessage(`Nieuwe activatiecode voor ${selectedParticipant.name}: ${result.activationCode}. Geef deze code door aan de deelnemer.`)}catch(error){setMessage(error instanceof Error?error.message:'Een nieuwe activatiecode maken is niet gelukt.')}finally{setRenewBusy(false)}};
 if(mode==='new-trajectory')return <AdminForm title="Nieuw traject" onSubmit={create} onCancel={()=>setMode('list')}><label>Opdrachtgever<select name="commissioner" required value={commissioners.find(item=>item.code===selectedCommissionerCode)?.name||''} onChange={event=>setSelectedCommissionerCode(commissioners.find(item=>item.name===event.target.value)?.code||'')}>{commissioners.map(item=><option value={item.name} key={item.code}>{item.name}</option>)}</select></label><label>Automatisch gegenereerde trajectcode<input value={generatedCode} readOnly aria-readonly="true"/></label><TrajectoryFields hideCommissioner availableCoaches={availableCoaches}/></AdminForm>;
 if(mode==='edit-trajectory'&&trajectory)return <AdminForm title="Traject wijzigen" onSubmit={edit} onCancel={()=>setMode('list')} message={message}><label>Trajectcode (kan niet worden gewijzigd)<input value={trajectory.code} readOnly aria-readonly="true"/></label><TrajectoryFields trajectory={trajectory} availableCoaches={availableCoaches}/></AdminForm>;
 if(mode==='new-participant'&&trajectory)return <AdminForm title={`Deelnemer toevoegen aan ${trajectory.name}`} onSubmit={add} onCancel={()=>setMode('list')} message={message}><label>Voor- en achternaam<input name="name" required/></label><label>E-mailadres<input name="email" type="email" required/></label><label>Telefoonnummer<input name="phone" type="tel"/></label><label>Woonplaats<input name="city" maxLength={120}/></label><label>Geboortedatum<input name="birthDate" type="date" max={new Date().toLocaleDateString('sv-SE')} required/></label><label>Eigen begeleider<select name="coachId" required defaultValue=""><option value="" disabled>Selecteer een begeleider</option>{trajectory.coaches.map(coach=><option value={coach.id} key={coach.id}>{coach.name}</option>)}</select></label></AdminForm>;
 if(mode==='participant-created'&&createdParticipant)return <section className="admin-form"><h2>{createdParticipant.name} is toegevoegd</h2><p>Geef deze activatiecode door aan de deelnemer. De code wordt na het sluiten van dit scherm niet opnieuw getoond.</p><p className="dashboard-message">Activatiecode: <strong>{createdParticipant.activationCode}</strong></p>{message&&<p className="dashboard-message">{message}</p>}<button className="release-button" onClick={()=>{setCreatedParticipant(null);setMode('list')}}>Terug naar trajecten</button></section>;
 if(mode==='edit-participant'&&trajectory&&selectedParticipant)return <AdminForm title={`Deelnemer wijzigen: ${selectedParticipant.name}`} onSubmit={updateParticipant} onCancel={()=>setMode('list')} message={message}><p>Accountactivatie: {selectedParticipant.activatedAt?`geactiveerd op ${selectedParticipant.activatedAt}`:'nog niet geactiveerd'}. Dit staat los van de toegang tot het account.</p><label>Voor- en achternaam<input name="name" required defaultValue={selectedParticipant.name}/></label><label>E-mailadres<input name="email" type="email" required defaultValue={selectedParticipant.email}/></label><label>Telefoonnummer<input name="phone" type="tel" defaultValue={selectedParticipant.phone}/></label><label>Woonplaats<input name="city" maxLength={120} defaultValue={selectedParticipant.city}/></label><label>Geboortedatum<input name="birthDate" type="date" max={new Date().toLocaleDateString('sv-SE')} required defaultValue={selectedParticipant.birthDate}/></label><label>Eigen begeleider<select name="coachId" required defaultValue={selectedParticipant.coachId}><option value="" disabled>Selecteer een begeleider</option>{trajectory.coaches.map(coach=><option value={coach.id} key={coach.id}>{coach.name}</option>)}</select></label><label className="check"><input name="active" type="checkbox" defaultChecked={selectedParticipant.active}/><span>Account actief</span></label><button type="button" className="close-button" disabled={renewBusy} onClick={()=>void renew()}>{renewBusy?'Activatiecode maken…':'Nieuwe activatiecode maken'}</button></AdminForm>;
 return <section className="admin-panel">
  <header><div><h2>Trajecten en deelnemers</h2><p>Beheer de trajecten waarvoor jij verantwoordelijk bent.</p></div><button onClick={()=>setMode('new-trajectory')}>Nieuw traject</button></header>
  {message&&<p className="dashboard-message">{message}</p>}
  <div className="admin-trajectories">{trajectories.map(item=>{
   const visibleParticipants=item.participants.filter(participant=>showInactiveParticipants||participant.active!==false);
   const activeCount=item.participants.filter(participant=>participant.active!==false).length;
   return <article className={item.code===selected?'selected':''} key={item.code}>
    <button className="trajectory-select" onClick={()=>onSelected(item.code)}><strong>{item.name}</strong><span>{item.code} · {item.startDate} t/m {item.endDate}</span><small>{activeCount} actieve deelnemers · {item.status==='active'?'Actief':item.status==='planned'?'Gepland':'Afgerond'}</small><small>Begeleiders: {item.coaches.map(coach=>coach.name).join(', ')||'nog niet gekoppeld'}</small></button>
    {item.code===selected&&<><div><button onClick={()=>setMode('edit-trajectory')}>Traject wijzigen</button><button onClick={()=>{setMessage('');setMode('new-participant')}}>Deelnemer toevoegen</button></div><section className="trajectory-members"><h3>Gekoppelde deelnemers</h3><label className="check"><input type="checkbox" checked={showInactiveParticipants} onChange={event=>setShowInactiveParticipants(event.target.checked)}/><span>Toon ook inactieve deelnemers</span></label>{visibleParticipants.length?<><p>Kies een deelnemer om de gegevens of begeleider te wijzigen.</p><ul>{visibleParticipants.map(participant=><li key={participant.id}><button className="participant-edit" onClick={()=>{setSelectedParticipantId(participant.id);setMode('edit-participant')}}><strong>{participant.name}</strong><span>Eigen begeleider: {item.coaches.find(coach=>coach.id===participant.coachId)?.name||'nog niet gekoppeld'}</span><span>Account: {participant.active!==false?'actief':'inactief'}</span><span>Activatie: {participant.activatedAt?`geactiveerd op ${participant.activatedAt}`:'nog niet geactiveerd'}</span><em>Deelnemer wijzigen</em></button></li>)}</ul></>:<p>{item.participants.length?'Er zijn geen actieve deelnemers.':'Nog geen deelnemers aan dit traject gekoppeld.'}</p>}</section></>}
   </article>
  })}</div>
 </section>;
}
function TrajectoryFields({trajectory,hideCommissioner=false,availableCoaches}:{trajectory?:DashboardTrajectory;hideCommissioner?:boolean;availableCoaches:DashboardCoach[]}){return <><label>Naam traject<input name="name" required defaultValue={trajectory?.name}/></label>{!hideCommissioner&&<label>Opdrachtgever (kan niet worden gewijzigd)<input name="commissioner" value={trajectory?.commissionerName||''} readOnly aria-readonly="true"/></label>}<label>Startdatum<input name="start" type="date" required defaultValue={toIsoDate(trajectory?.startDate)}/></label><label>Einddatum<input name="end" type="date" required defaultValue={toIsoDate(trajectory?.endDate)}/></label><fieldset className="coach-selection"><legend>Begeleiders voor dit traject</legend>{availableCoaches.map(coach=><label className="check" key={coach.id}><input type="checkbox" name="coaches" value={coach.id} defaultChecked={trajectory?.coaches.some(item=>item.id===coach.id)}/><span>{coach.name}</span></label>)}</fieldset></>}
function AdminForm({title,onSubmit,onCancel,children,message}:{title:string;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void;children:ReactNode;message?:string}){return <section className="admin-form"><h2>{title}</h2>{message&&<p className="dashboard-message">{message}</p>}<form onSubmit={onSubmit}>{children}<div><button className="release-button">Opslaan</button><button type="button" className="close-button" onClick={onCancel}>Annuleren</button></div></form></section>}
