import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import type { DashboardRepository, DashboardTrajectory } from './domain';

export function DashboardAdmin({repository,trajectories,selected,onSelected,onChanged}:{repository:DashboardRepository;trajectories:DashboardTrajectory[];selected:string;onSelected:(code:string)=>void;onChanged:()=>Promise<void>}){
 const[mode,setMode]=useState<'list'|'new-trajectory'|'edit-trajectory'|'new-participant'>('list');const[message,setMessage]=useState('');const trajectory=trajectories.find(t=>t.code===selected);
 const fields=(form:HTMLFormElement)=>{const data=new FormData(form);return {name:String(data.get('name')||'').trim(),commissionerName:String(data.get('commissioner')||'').trim(),startDate:String(data.get('start')||'').trim(),endDate:String(data.get('end')||'').trim()}};
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await repository.createTrajectory({code:String(data.get('code')||'').trim(),...fields(event.currentTarget)});await onChanged();setMode('list');setMessage('Het traject is toegevoegd.')}catch(error){setMessage(error instanceof Error?error.message:'Toevoegen is niet gelukt.')}};
 const edit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!trajectory)return;try{await repository.updateTrajectory(trajectory.code,fields(event.currentTarget));await onChanged();setMode('list');setMessage('De trajectgegevens zijn bijgewerkt.')}catch(error){setMessage(error instanceof Error?error.message:'Wijzigen is niet gelukt.')}};
 const add=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!trajectory)return;const data=new FormData(event.currentTarget);try{await repository.addParticipant(trajectory.code,{name:String(data.get('name')||'').trim(),email:String(data.get('email')||'').trim(),phone:String(data.get('phone')||'').trim()});await onChanged();setMode('list');setMessage('De deelnemer is toegevoegd.')}catch(error){setMessage(error instanceof Error?error.message:'Toevoegen is niet gelukt.')}};
 if(mode==='new-trajectory')return <AdminForm title="Nieuw traject" onSubmit={create} onCancel={()=>setMode('list')}><label>Trajectcode<input name="code" required placeholder="Bijvoorbeeld MW-RSD-003"/></label><TrajectoryFields/></AdminForm>;
 if(mode==='edit-trajectory'&&trajectory)return <AdminForm title="Traject wijzigen" onSubmit={edit} onCancel={()=>setMode('list')}><TrajectoryFields trajectory={trajectory}/></AdminForm>;
 if(mode==='new-participant'&&trajectory)return <AdminForm title={`Deelnemer toevoegen aan ${trajectory.name}`} onSubmit={add} onCancel={()=>setMode('list')}><label>Voor- en achternaam<input name="name" required/></label><label>E-mailadres<input name="email" type="email" required/></label><label>Telefoonnummer<input name="phone" type="tel"/></label></AdminForm>;
 return <section className="admin-panel"><header><div><h2>Trajecten en deelnemers</h2><p>Beheer de trajecten waarvoor jij verantwoordelijk bent.</p></div><button onClick={()=>setMode('new-trajectory')}>Nieuw traject</button></header>{message&&<p className="dashboard-message">{message}</p>}<div className="admin-trajectories">{trajectories.map(item=><article className={item.code===selected?'selected':''} key={item.code}><button className="trajectory-select" onClick={()=>onSelected(item.code)}><strong>{item.name}</strong><span>{item.code} · {item.startDate} t/m {item.endDate}</span><small>{item.participants.length} deelnemers · {item.status==='active'?'Actief':item.status==='planned'?'Gepland':'Afgerond'}</small></button>{item.code===selected&&<div><button onClick={()=>setMode('edit-trajectory')}>Traject wijzigen</button><button onClick={()=>setMode('new-participant')}>Deelnemer toevoegen</button></div>}</article>)}</div></section>;
}
function TrajectoryFields({trajectory}:{trajectory?:DashboardTrajectory}){return <><label>Naam traject<input name="name" required defaultValue={trajectory?.name}/></label><label>Opdrachtgever<input name="commissioner" required defaultValue={trajectory?.commissionerName}/></label><label>Startdatum (dd-mm-jjjj)<input name="start" required pattern="\d{2}-\d{2}-\d{4}" defaultValue={trajectory?.startDate}/></label><label>Einddatum (dd-mm-jjjj)<input name="end" required pattern="\d{2}-\d{2}-\d{4}" defaultValue={trajectory?.endDate}/></label></>}
function AdminForm({title,onSubmit,onCancel,children}:{title:string;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void;children:ReactNode}){return <section className="admin-form"><h2>{title}</h2><form onSubmit={onSubmit}>{children}<div><button className="release-button">Opslaan</button><button type="button" className="close-button" onClick={onCancel}>Annuleren</button></div></form></section>}
