import { useEffect, useState } from 'react';
import type { AnswerRepository } from './domain';
import { measurementSubjects } from './trajectoryDefinition';
import { saveErrorMessage } from './saveError';

type Scores=Record<string,number>;
const directions=[['Werk','Een baan vinden die bij mij past.'],['Opleiding','Verder leren via een opleiding, BOL of BBL.'],['Werk én opleiding','Werken combineren met leren.'],['Verdere begeleiding','Eerst extra ondersteuning bij mijn volgende stap.'],['Iets anders','Een andere passende route bespreken.']] as const;
const Eye=()=> <svg className="eye-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/></svg>;
const Private=()=> <div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen dit antwoord zien.</span></div>;
const Shared=()=> <div className="visibility-note"><Eye/><span>Jij, je begeleiders en de RSD kunnen deze antwoorden zien.</span></div>;

export function StepSevenFlow({repository,participantId,trajectoryCode,onClose,onHome,outcome}:{repository:AnswerRepository;participantId:string;trajectoryCode:string;onClose:()=>void;onHome:()=>void;outcome?:{category:string;summary:string;status:'provisional'|'final'}}){
 const[stage,setStage]=useState<'intro'|'directions'|'prepare'|'measurement'|'waiting'|'result'>('intro');const[selected,setSelected]=useState<string[]>([]);const[preparation,setPreparation]=useState('');const[scores,setScores]=useState<Scores>({});const[notice,setNotice]=useState('');
 useEffect(()=>{if(outcome?.status==='final')setStage('result');if(stage==='directions')repository.get(participantId,trajectoryCode,'s7-direction').then(a=>setSelected(Array.isArray(a?.value)?a.value:[]));if(stage==='prepare')repository.get(participantId,trajectoryCode,'s7-prepare').then(a=>setPreparation(typeof a?.value==='string'?a.value:''));if(stage==='measurement')repository.get(participantId,trajectoryCode,'s7-measurement').then(a=>setScores(a?.value&&typeof a.value==='object'&&!Array.isArray(a.value)?Object.fromEntries(Object.entries(a.value).map(([k,v])=>[k,Number(v)])):{}))},[outcome?.status,participantId,repository,stage,trajectoryCode]);
 const save=async(id:string,value:string|string[]|Scores)=>{setNotice('Opslaan…');try{await repository.save({participantId,trajectoryCode,activityId:id,value,updatedAt:new Date().toISOString()});setNotice('Automatisch opgeslagen')}catch(reason){setNotice(saveErrorMessage(reason))}};
 const toggle=(item:string)=>{const next=selected.includes(item)?selected.filter(x=>x!==item):[...selected,item];setSelected(next);void save('s7-direction',next)};
 const score=(subject:string,value:number)=>{const next={...scores,[subject]:value};setScores(next);void save('s7-measurement',next)};
 if(stage==='intro')return <section className="step-flow"><span className="eyebrow">Stap 7 · Mogelijkheden en afronding</span><h1>Bekijk waar jij naartoe wilt</h1><p>Je kijkt vooruit en bereidt het afsluitende gesprek met je begeleider voor.</p><section className="flow-card"><h2>In deze laatste stap</h2><ol className="numbered-info"><li>Kies welke richtingen je wilt bespreken.</li><li>Bereid het gesprek met je begeleider voor.</li><li>Vul opnieuw in waar je nu staat.</li><li>Na het gesprek komt jouw volgende stap in de app.</li></ol></section><button className="flow-primary" onClick={()=>setStage('directions')}>Bekijk mijn mogelijkheden</button><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
 if(stage==='directions')return <section className="step-flow"><span className="eyebrow">Stap 7 · 1 van 3</span><h1>Welke richting wil je bespreken?</h1><p>Je mag meer dan één richting kiezen.</p><section className="flow-card"><div className="choice-list">{directions.map(([title,text])=><button className={`choice-card ${selected.includes(title)?'selected':''}`} onClick={()=>toggle(title)} key={title}><span>{selected.includes(title)?'✓':''}</span><div><strong>{title}</strong><p>{text}</p></div></button>)}</div><Private/>{notice&&<div className="save-state">{notice}</div>}</section><button className="flow-primary" onClick={()=>setStage('prepare')}>Volgende</button><button className="flow-secondary" onClick={()=>setStage('intro')}>Terug naar uitleg</button></section>;
 if(stage==='prepare')return <section className="step-flow"><span className="eyebrow">Stap 7 · 2 van 3</span><h1>Bereid je gesprek voor</h1><p>Hierna bespreek je samen met je begeleider wat een passende volgende stap is.</p><section className="flow-card question-card"><span className="question-count">Jouw gesprek</span><h2>Wat wil jij zeker bespreken?</h2><p>Denk aan wat je graag wilt, waarover je twijfelt en welke hulp je misschien nodig hebt.</p><textarea value={preparation} onChange={e=>setPreparation(e.target.value)} placeholder="Schrijf hier wat je wilt bespreken…"/><Private/></section><button className="flow-primary" onClick={()=>void save('s7-prepare',preparation).then(()=>setStage('measurement'))}>Volgende</button><button className="flow-secondary" onClick={()=>setStage('directions')}>Vorige</button></section>;
 if(stage==='measurement')return <section className="step-flow"><span className="eyebrow">Stap 7 · 3 van 3</span><h1>Waar sta je nu?</h1><p>Kies voor ieder onderwerp een cijfer van 1 tot 10. 1 is helemaal niet en 10 is helemaal wel.</p><section className="flow-card"><div className="measurement-list">{measurementSubjects.map(subject=><fieldset key={subject}><legend>{subject}</legend><div className="score-row">{[1,2,3,4,5,6,7,8,9,10].map(value=><label key={value}><input type="radio" name={subject} checked={scores[subject]===value} onChange={()=>score(subject,value)}/><span>{value}</span></label>)}</div></fieldset>)}</div><Shared/>{notice&&<div className="save-state">{notice}</div>}</section><button className="flow-primary" onClick={()=>setStage('waiting')}>Opslaan en verder</button><button className="flow-secondary" onClick={()=>setStage('prepare')}>Vorige</button></section>;
 if(stage==='waiting')return <section className="step-flow"><span className="eyebrow">Stap 7 · Voorbereiding klaar</span><h1>Je bent klaar voor het eindgesprek</h1><p>Je bespreekt samen met je begeleider welke volgende stap bij jou past.</p><section className="flow-card"><h2>Na het gesprek</h2><p>Je begeleider zet de afspraken en het uitstroomadvies in de app. Nadat het definitieve advies is vrijgegeven, verschijnt jouw volgende stap hier.</p><Shared/><div className="notice-box">Het advies wordt door je begeleiders opgesteld. De AI-assistent neemt hierover geen beslissingen.</div></section><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
 return <section className="step-flow"><span className="eyebrow">Jouw traject · Afgerond</span><h1>Dit is jouw volgende stap</h1><p>Deze afspraken hebben jij en je begeleider samen gemaakt.</p><section className="flow-card final-result"><span className="question-count">Jouw richting</span><h2>{outcome?.category}</h2><p>{outcome?.summary}</p><div className="visibility-note"><Eye/><span>Jij, je begeleiders en de RSD kunnen deze uitkomst zien.</span></div></section><button className="flow-primary orange" onClick={onHome}>Terug naar Home</button></section>;
}
