import { useEffect, useState } from 'react';
import type { AnswerRepository } from './domain';
import { openAiAssistant } from './aiNavigation';
import { saveErrorMessage } from './saveError';

const questions=[
 {id:'s6-about',title:'Vertel iets over jezelf',question:'Wie ben jij?',help:'Denk bijvoorbeeld aan wat je leuk vindt, waar je goed in bent en wat voor werk je zoekt.',placeholder:'Schrijf hier wat je wilt vertellen…'},
 {id:'s6-fit',title:'Waarom past dit werk bij jou?',question:'Wat past goed?',help:'Denk aan de taken, jouw kwaliteiten en waarom je dit werk graag wilt doen.',placeholder:'Schrijf hier jouw antwoord…'},
 {id:'s6-difficult',title:'Een lastig moment bespreken',question:'Welke situatie kun jij noemen?',help:'Vertel kort wat er gebeurde, wat jij deed en wat je ervan hebt geleerd. Dit mag ook een voorbeeld van school, stage of thuis zijn.',placeholder:'Beschrijf hier een situatie…'},
 {id:'s6-own-questions',title:'Welke vragen wil jij stellen?',question:'Wat wil jij graag weten?',help:'Denk aan de taken, het team, de werktijden, begeleiding of hoe een werkdag eruitziet.',placeholder:'Schrijf hier jouw vragen…'}
] as const;
const Eye=()=> <svg className="eye-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/></svg>;
const Visibility=()=> <div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen dit antwoord zien.</span></div>;

export function StepSixFlow({repository,participantId,trajectoryCode,onClose,onComplete}:{repository:AnswerRepository;participantId:string;trajectoryCode:string;onClose:()=>void;onComplete:()=>Promise<void>}){
 const[stage,setStage]=useState<'intro'|'overview'|'questions'|'done'>('intro');const[index,setIndex]=useState(0);const[value,setValue]=useState('');const[loaded,setLoaded]=useState(false);const[saveState,setSaveState]=useState('');const[aiMessage,setAiMessageState]=useState('');const question=questions[index];const setAiMessage=(message:string)=>{if(message.includes('AI-bouwstap'))openAiAssistant(`Help mij mijn antwoord voor te bereiden op deze vraag: ${question.question}${value?` Mijn eerste antwoord is: ${value}`:''}`);else setAiMessageState(message)};
 useEffect(()=>{if(stage!=='questions')return;let active=true;setLoaded(false);repository.get(participantId,trajectoryCode,question.id).then(answer=>{if(!active)return;setValue(typeof answer?.value==='string'?answer.value:'');setSaveState(answer?'Automatisch opgeslagen':'');setLoaded(true)});return()=>{active=false}},[participantId,question.id,repository,stage,trajectoryCode]);
 useEffect(()=>{if(stage!=='questions'||!loaded)return;setSaveState('Opslaan…');const timer=window.setTimeout(()=>repository.save({participantId,trajectoryCode,activityId:question.id,value,updatedAt:new Date().toISOString()}).then(()=>setSaveState('Automatisch opgeslagen')).catch(reason=>setSaveState(saveErrorMessage(reason))),450);return()=>window.clearTimeout(timer)},[loaded,participantId,question.id,repository,stage,trajectoryCode,value]);
 const save=async()=>{setSaveState('Opslaan…');try{await repository.save({participantId,trajectoryCode,activityId:question.id,value,updatedAt:new Date().toISOString()});setSaveState('Automatisch opgeslagen');if(index===questions.length-1){await onComplete();setStage('done')}else{setIndex(i=>i+1);setAiMessage('')}}catch(reason){setSaveState(saveErrorMessage(reason))}};
 if(stage==='intro')return <section className="step-flow"><span className="eyebrow">Stap 6 · Een gesprek voorbereiden</span><h1>Bereid je gesprek rustig voor</h1><p>Je bekijkt welke vragen je kunt krijgen en denkt alvast na over jouw antwoorden.</p><section className="flow-card"><h2>Goed om te weten</h2><ol className="numbered-info"><li>Je hoeft nog geen perfecte antwoorden te geven.</li><li>Je kunt de AI-assistent gebruiken om je antwoorden voor te bereiden.</li><li>Het gesprek zelf oefen je tijdens de groepsbijeenkomst.</li></ol><Visibility/></section><button className="flow-primary" onClick={()=>setStage('overview')}>Bekijk de vragen</button><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
 if(stage==='overview')return <section className="step-flow"><span className="eyebrow">Stap 6 · 1 van 5</span><h1>Welke vragen kun je krijgen?</h1><p>Deze vragen komen vaak voor in een gesprek over werk.</p><section className="flow-card interview-list">{questions.map((item,i)=><article key={item.id}><span>{i+1}</span><div><strong>{item.title}</strong><p>{item.help}</p></div></article>)}</section><button className="flow-primary" onClick={()=>setStage('questions')}>Mijn antwoorden voorbereiden</button><button className="flow-secondary" onClick={()=>setStage('intro')}>Terug naar uitleg</button></section>;
 if(stage==='done')return <section className="step-flow"><span className="eyebrow">Stap 6 · Voorbereiding klaar</span><h1>Je bent voorbereid op het oefenen</h1><p>Tijdens de groepsbijeenkomst ga je samen met de anderen een gesprek oefenen.</p><section className="flow-card"><h2>Neem jouw voorbereiding mee</h2><p>Je kunt jouw antwoorden tijdens het oefenen gebruiken. Ze zijn een hulpmiddel; je hoeft ze niet uit je hoofd te leren.</p><div className="notice-box">Na het oefenen kun je je antwoorden altijd nog aanpassen.</div><Visibility/></section><button className="flow-primary orange" onClick={onClose}>Terug naar mijn route</button><button className="flow-secondary" onClick={()=>{setIndex(0);setStage('questions')}}>Bekijk mijn antwoorden</button></section>;
 return <section className="step-flow"><span className="eyebrow">Stap 6 · {index+2} van 5</span><h1>{question.title}</h1><p>{question.help}</p><section className="flow-card question-card"><span className="question-count">Jouw voorbereiding</span><h2>{question.question}</h2><textarea value={value} onChange={event=>setValue(event.target.value)} placeholder={question.placeholder}/><Visibility/><div className="ai-helper"><strong>Hulp van de AI-assistent</strong><p>Vraag om een voorbeeld, tips of hulp om jouw antwoord duidelijker te maken.</p><button className="flow-secondary" onClick={()=>setAiMessage('De AI-assistent wordt in de AI-bouwstap aan dit antwoord gekoppeld.')}>Vraag de AI-assistent</button>{aiMessage&&<p className="notice-box">{aiMessage}</p>}</div><div className={`save-state ${saveState.includes('mislukt')?'error':'saved'}`}>{saveState}</div></section><button className="flow-primary" onClick={()=>void save()}>{index===questions.length-1?'Rond de voorbereiding af':'Volgende'}</button><button className="flow-secondary" onClick={()=>index===0?setStage('overview'):setIndex(i=>i-1)}>{index===0?'Terug naar overzicht':'Vorige'}</button></section>;
}
