import { useEffect, useState } from 'react';
import type { AnswerRepository } from './domain';

const sources=[['Websites met banen','Zoek op werk, plaats en het aantal uren.'],['Bij een werkgever','Kijk op de website of loop eens binnen.'],['Uitzendbureau','Een uitzendbureau kan met je meedenken.'],['Via mensen die je kent','Vraag familie, vrienden of bekenden of zij iets weten.']] as const;
const preferences=[['Het werk past bij mij','De taken lijken mij leuk en passen bij wat ik kan.'],['De plek is goed bereikbaar','Ik kan er zonder veel gedoe komen.'],['De uren passen bij mij','Het aantal uren en de werktijden passen bij mijn situatie.'],['Het bedrijf past bij mij','De grootte, sfeer en manier van samenwerken voelen goed.']] as const;
const ids=['s5-sources','s5-fit','s5-example','s5-match','s5-reaction-example','s5-reaction'];
const Eye=()=> <svg className="eye-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/></svg>;
const Visibility=()=> <div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen dit antwoord zien.</span></div>;
function Vacancy(){return <article className="vacancy-card"><span className="question-count">Voorbeeld van een baan</span><h2>Verkoopmedewerker kledingwinkel</h2><p>Kledingwinkel · Zeist · 24–32 uur</p><dl><div><dt>Wat ga je doen?</dt><dd>Klanten helpen, kleding netjes houden en achter de kassa werken.</dd></div><div><dt>Wat vragen ze?</dt><dd>Je bent vriendelijk, helpt graag mensen en vindt samenwerken prettig.</dd></div><div><dt>Het bedrijf</dt><dd>Een middelgrote winkel met een jong team en een informele sfeer.</dd></div></dl></article>}

export function StepFiveFlow({repository,participantId,trajectoryCode,onClose}:{repository:AnswerRepository;participantId:string;trajectoryCode:string;onClose:()=>void}){
 const[stage,setStage]=useState<'intro'|'parts'|'done'>('intro');const[index,setIndex]=useState(0);const[selected,setSelected]=useState<string[]>([]);const[match,setMatch]=useState('');const[reaction,setReaction]=useState('');const[notice,setNotice]=useState('');
 useEffect(()=>{if(stage!=='parts')return;repository.get(participantId,trajectoryCode,ids[index]).then(answer=>{const stored=answer?.value;setSelected(index<2&&Array.isArray(stored)?stored:[]);if(index===3)setMatch(typeof stored==='string'?stored:'');if(index===5)setReaction(typeof stored==='string'?stored:'');setNotice(answer?'Automatisch opgeslagen':'')})},[index,participantId,repository,stage,trajectoryCode]);
 const value=()=>index<2?selected:index===3?match:index===5?reaction:'';
 const save=async(nextValue=value())=>{setNotice('Opslaan…');try{await repository.save({participantId,trajectoryCode,activityId:ids[index],value:nextValue,updatedAt:new Date().toISOString()});setNotice('Automatisch opgeslagen')}catch{setNotice('Opslaan is niet gelukt')}};
 const next=async()=>{await save();if(index===5)setStage('done');else{setIndex(i=>i+1);setSelected([]);setNotice('')}};
 const toggle=(item:string)=>{const nextValues=selected.includes(item)?selected.filter(x=>x!==item):[...selected,item];setSelected(nextValues);void save(nextValues)};
 const choices=(items:readonly(readonly[string,string])[])=> <div className="choice-list">{items.map(([title,text])=><button className={`choice-card ${selected.includes(title)?'selected':''}`} key={title} onClick={()=>toggle(title)}><span>{selected.includes(title)?'✓':''}</span><div><strong>{title}</strong><p>{text}</p></div></button>)}</div>;
 if(stage==='intro')return <section className="step-flow"><span className="eyebrow">Stap 5 · Werk zoeken en reageren</span><h1>Zo vind je werk dat bij je past</h1><p>Je ontdekt waar je werk kunt vinden, waar je op kunt letten en hoe je kunt reageren.</p><section className="flow-card"><h2>Dit ga je doen</h2><ol className="numbered-info"><li>Ontdekken waar je werk kunt vinden.</li><li>Bekijken wat voor werk en welk bedrijf bij jou passen.</li><li>Een voorbeeld bekijken en een reactie voorbereiden.</li></ol><div className="notice-box">Je hoeft in deze stap nog niet echt te solliciteren. Als je een passende baan vindt, kan dat natuurlijk wel.</div></section><button className="flow-primary" onClick={()=>setStage('parts')}>Begin met deze stap</button><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
 if(stage==='done')return <section className="step-flow"><span className="eyebrow">Stap 5 · Klaar</span><h1>Je weet hoe je werk kunt zoeken en reageren</h1><p>Je kunt nu gerichter kijken welke baan en welk bedrijf bij jou passen.</p><section className="flow-card"><h2>Mooi gedaan</h2><p>Heb je een baan gevonden waarop je echt wilt reageren? Bespreek dit met je begeleider of gebruik de AI-assistent.</p><Visibility/></section><button className="flow-primary orange" onClick={onClose}>Terug naar mijn route</button></section>;
 const screens=[<><h2>Waar kun je werk vinden?</h2><p>Kies wat jij zou willen proberen.</p>{choices(sources)}<Visibility/></>,<><h2>Wat past bij jou?</h2><p>Waar wil jij op letten als je naar werk kijkt?</p>{choices(preferences)}<Visibility/></>,<><h2>Een baan bekijken</h2><p>Lees rustig wat het werk inhoudt en wat het bedrijf zoekt.</p><Vacancy/></>,<><h2>Past deze baan bij mij?</h2><p>Denk aan het werk én aan het bedrijf.</p><Vacancy/><label className="field-label">Wat denk jij?<select value={match} onChange={e=>setMatch(e.target.value)}><option value="">Kies een antwoord</option><option>Ja</option><option>Misschien</option><option>Nee</option></select></label><Visibility/></>,<><h2>Hoe kun je reageren?</h2><p>Een reactie mag kort, duidelijk en persoonlijk zijn.</p><div className="reaction-example"><p>Hoi, de baan als verkoopmedewerker in jullie kledingwinkel lijkt mij heel leuk en past denk ik goed bij mij. Ik help graag mensen en zou graag kennismaken.</p><p>Groet,<br/>Sam</p></div></>,<><h2>Jouw reactie voorbereiden</h2><p>Schrijf hoe jij op deze baan zou kunnen reageren.</p><textarea value={reaction} onChange={e=>setReaction(e.target.value)} placeholder="Schrijf hier jouw reactie…"/><Visibility/><button className="flow-secondary" onClick={()=>setNotice('De AI-assistent wordt later aan deze reactie gekoppeld.')}>Vraag de AI-assistent</button></>];
 return <section className="step-flow"><span className="eyebrow">Stap 5 · {index+1} van 6</span><section className="flow-card question-card">{screens[index]}{notice&&<div className="save-state">{notice}</div>}</section><button className="flow-primary" onClick={()=>void next()}>{index===5?'Rond deze stap af':'Volgende'}</button><button className="flow-secondary" onClick={()=>index===0?setStage('intro'):setIndex(i=>i-1)}>{index===0?'Terug naar uitleg':'Vorige'}</button></section>;
}
