import { useEffect, useState } from 'react';
import type { AnswerRepository } from './domain';

type CvData = Record<string, string>;
const parts = [
  { id:'s3-details', heading:'Jouw gegevens', title:'Kloppen jouw gegevens?', help:'Een aantal velden zijn al ingevuld. Wil je kijken of deze kloppen en waar nodig de gegevens aanpassen of aanvullen.', fields:[['name','Voor- en achternaam'],['city','Woonplaats'],['age','Leeftijd'],['phone','Telefoonnummer'],['email','E-mailadres']] },
  { id:'s3-about', heading:'Dit ben ik', title:'Vertel iets over jezelf', help:'Met een paar korte antwoorden maken we straks een persoonlijke tekst voor je cv.', fields:[['description','Hoe zou je jezelf omschrijven?'],['strengths','Waar ben je goed in?'],['energy','Wat vind je leuk en waar krijg je energie van?']] },
  { id:'s3-education', heading:'Opleiding en leren', title:'Voeg je opleiding toe', help:'Ook een opleiding die je niet hebt afgerond kan op je cv.', skippable:true, fields:[['education','Naam van de opleiding of richting'],['school','School of opleider'],['educationStatus','Status van de opleiding']] },
  { id:'s3-experience', heading:'Mijn ervaring', title:'Voeg je ervaring toe', help:'Werk, een bijbaan, stage en vrijwilligerswerk kunnen allemaal op je cv.', skippable:true, fields:[['experienceType','Soort ervaring'],['organization','Bedrijf of organisatie'],['experienceDescription','Wat deed je daar?']] },
  { id:'s3-extra', heading:'Extra informatie', title:'Wil je nog iets toevoegen?', help:'Dit onderdeel is niet verplicht. Vul alleen in wat voor jou van toepassing is.', skippable:true, fields:[['drivingLicense','Rijbewijs'],['languages','Talen'],['certificates','Certificaten']] },
] as const;

const Eye = () => <svg className="eye-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/></svg>;

export function StepThreeFlow({ repository, participantId, trajectoryCode, onClose }: { repository:AnswerRepository; participantId:string; trajectoryCode:string; onClose:()=>void }) {
  const [stage,setStage]=useState<'intro'|'parts'|'preview'>('intro');
  const [index,setIndex]=useState(0);
  const [data,setData]=useState<CvData>({name:'Sam de Jong',city:'Zeist',age:'20',phone:'06 12345678',email:'sam@voorbeeld.nl'});
  const [loaded,setLoaded]=useState(false);
  const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle');
  const [message,setMessage]=useState('');
  const part=parts[index];
  const partData=()=>Object.fromEntries(part.fields.map(([key])=>[key,data[key]||'']));

  useEffect(()=>{ if(stage!=='parts') return; let active=true; setLoaded(false); repository.get(participantId,trajectoryCode,part.id).then(answer=>{ if(!active)return; const saved=answer?.value; if(saved&&typeof saved==='object'&&!Array.isArray(saved)) setData(current=>({...current,...Object.fromEntries(Object.entries(saved).map(([key,value])=>[key,String(value)]))})); setLoaded(true); }); return()=>{active=false}; },[index,part.id,participantId,repository,stage,trajectoryCode]);
  useEffect(()=>{ if(stage!=='parts'||!loaded)return; setSaveState('saving'); const timer=window.setTimeout(()=>repository.save({participantId,trajectoryCode,activityId:part.id,value:partData(),updatedAt:new Date().toISOString()}).then(()=>setSaveState('saved')).catch(()=>setSaveState('error')),450); return()=>window.clearTimeout(timer); },[data,loaded,part.id,participantId,repository,stage,trajectoryCode]);

  const move=async(direction:1|-1)=>{ try{await repository.save({participantId,trajectoryCode,activityId:part.id,value:partData(),updatedAt:new Date().toISOString()});setSaveState('saved');if(direction===1&&index===parts.length-1)setStage('preview');else setIndex(current=>current+direction);}catch{setSaveState('error')} };
  const skip=async()=>{const cleared={...data};part.fields.forEach(([key])=>delete cleared[key]);setData(cleared);try{await repository.save({participantId,trajectoryCode,activityId:part.id,value:{},updatedAt:new Date().toISOString()});if(index===parts.length-1)setStage('preview');else setIndex(current=>current+1)}catch{setSaveState('error')}};
  const introduction=[data.description,data.strengths,data.energy].filter(Boolean).join(' ')||'Nog niet ingevuld';
  const download=()=>{const text=`CV\n\n${data.name||'Jouw naam'}\n${[data.city,data.age&&`${data.age} jaar`,data.phone,data.email].filter(Boolean).join(' · ')}\n\nOver mij\n${introduction}\n\nOpleiding\n${[data.education,data.school,data.educationStatus].filter(Boolean).join(' · ')||'Nog niet ingevuld'}\n\nErvaring\n${[data.experienceType,data.organization,data.experienceDescription].filter(Boolean).join(' · ')||'Nog niet ingevuld'}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='mijn-cv.txt';link.click();URL.revokeObjectURL(url)};

  if(stage==='intro')return <section className="step-flow"><span className="eyebrow">Stap 3 · Maak je cv</span><h1>Maak jouw cv</h1><p>Je interesses, opleiding en ervaring kunnen allemaal op je cv.</p><section className="flow-card"><h2>We doen dit in zes onderdelen</h2><ol className="numbered-info"><li>Jouw gegevens</li><li>Dit ben ik</li><li>Opleiding en leren</li><li>Mijn ervaring</li><li>Extra informatie</li><li>Bekijk jouw cv</li></ol><div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen deze gegevens zien.</span></div></section><button className="flow-primary" onClick={()=>setStage('parts')}>Begin met mijn cv</button><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
  if(stage==='preview')return <section className="step-flow"><span className="eyebrow">Stap 3 · Onderdeel 6 van 6</span><h1>Bekijk jouw cv</h1><p>Controleer rustig of alles klopt.</p><section className="flow-card cv-preview"><h2>{data.name||'Jouw naam'}</h2><p>{[data.city,data.age&&`${data.age} jaar`,data.phone,data.email].filter(Boolean).join(' · ')}</p><h3>Over mij</h3><p>{introduction}</p><h3>Opleiding</h3><p>{[data.education,data.school,data.educationStatus].filter(Boolean).join(' · ')||'Nog niet ingevuld'}</p><h3>Ervaring</h3><p>{[data.experienceType,data.organization,data.experienceDescription].filter(Boolean).join(' · ')||'Nog niet ingevuld'}</p><h3>Extra</h3><p>{[data.drivingLicense,data.languages,data.certificates].filter(Boolean).join(' · ')||'Nog niet ingevuld'}</p><div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen jouw cv zien.</span></div></section><button className="flow-primary" onClick={download}>Download mijn cv</button><button className="flow-secondary" onClick={()=>setMessage('De AI-assistent voor cv-feedback wordt in de AI-bouwstap gekoppeld.')}>Laat de AI-assistent meekijken</button>{message&&<p className="notice-box">{message}</p>}<button className="flow-secondary" onClick={()=>{setIndex(0);setStage('parts')}}>Gegevens aanpassen</button><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
  return <section className="step-flow"><span className="eyebrow">Stap 3 · Onderdeel {index+1} van 6</span><h1>{part.heading}</h1><p>{part.help}</p><section className="flow-card cv-form"><span className="question-count">Jouw cv</span><h2>{part.title}</h2>{part.fields.map(([key,label])=><label key={key}>{label}{key==='description'||key==='strengths'||key==='energy'||key==='experienceDescription'?<textarea value={data[key]||''} onChange={event=>setData(current=>({...current,[key]:event.target.value}))}/>:<input type={key==='age'?'number':key==='email'?'email':key==='phone'?'tel':'text'} value={data[key]||''} onChange={event=>setData(current=>({...current,[key]:event.target.value}))}/>}</label>)}<div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen deze gegevens zien.</span></div><div className={`save-state ${saveState}`}>{{idle:'',saving:'Opslaan…',saved:'Automatisch opgeslagen',error:'Opslaan is niet gelukt'}[saveState]}</div></section><button className="flow-primary" onClick={()=>void move(1)}>{index===parts.length-1?'Opslaan en bekijk mijn cv':'Opslaan en verder'}</button>{part.skippable&&<button className="flow-link" onClick={()=>void skip()}>Dit onderdeel overslaan</button>}<button className="flow-secondary" onClick={()=>index===0?setStage('intro'):void move(-1)}>{index===0?'Terug naar uitleg':'Vorig onderdeel'}</button></section>;
}
