import { useEffect, useState } from 'react';
import type { AnswerRepository } from './domain';

const sources=[['Websites met banen','Zoek op werk, plaats en het aantal uren.'],['Bij een werkgever','Kijk op de website of loop eens binnen.'],['Uitzendbureau','Een uitzendbureau kan met je meedenken.'],['Via mensen die je kent','Vraag familie, vrienden of bekenden of zij iets weten.']] as const;
const preferences=[['Het werk past bij mij','De taken lijken mij leuk en passen bij wat ik kan.'],['De plek is goed bereikbaar','Ik kan er zonder veel gedoe komen.'],['De uren passen bij mij','Het aantal uren en de werktijden passen bij mijn situatie.'],['Het bedrijf past bij mij','De grootte, sfeer en manier van samenwerken voelen goed.']] as const;
const guidance:Record<string,{explanation:string;example:string;url?:string;linkLabel?:string}>={
 'Websites met banen':{explanation:'Op een website kun je zoeken op soort werk en plaats. Lees rustig wat je gaat doen en wat het bedrijf zoekt.',example:'Zoek bijvoorbeeld naar “winkelmedewerker Zeist” op Indeed, een vacaturesite.',url:'https://nl.indeed.com/',linkLabel:'Open Indeed'},
 'Bij een werkgever':{explanation:'Weet je bij welk bedrijf je graag zou werken? Kijk op de website van dat bedrijf of vraag of er werk is.',example:'Bijvoorbeeld op de website van een kledingwinkel in jouw buurt.'},
 'Uitzendbureau':{explanation:'Een uitzendbureau helpt bij het zoeken naar werk. Je kunt er binnenlopen of online zoeken. Vertel wat je leuk vindt en hoeveel uur je zoekt.',example:'Vraag bij een uitzendbureau welke banen in jouw omgeving passen.'},
 'Via mensen die je kent':{explanation:'Mensen om je heen weten soms waar iemand nodig is. Je mag gewoon vertellen wat voor werk je zoekt.',example:'Vraag bijvoorbeeld aan een vriend of familielid of die een bedrijf kent.'},
 'Het werk past bij mij':{explanation:'Kijk vooral naar de dagelijkse taken. Zou je die graag doen en denk je dat je dit werk kan of kan leren?',example:'Bij winkelwerk kun je denken aan klanten helpen, kleding netjes houden en achter de kassa werken.'},
 'De plek is goed bereikbaar':{explanation:'Bedenk hoe je bij het werk komt en of de reis voor jou haalbaar voelt.',example:'Kijk hoe lang je met de fiets of het openbaar vervoer onderweg bent.'},
 'De uren passen bij mij':{explanation:'Let op het aantal uren en de tijden waarop je zou werken.',example:'Een baan van 24 uur per week kan beter of minder passen dan een baan van 40 uur.'},
 'Het bedrijf past bij mij':{explanation:'Niet alleen het werk, maar ook de omgeving is belangrijk. Denk aan de grootte van het bedrijf, de sfeer en hoe collega’s samenwerken.',example:'Werk je liever in een klein team of in een grote winkel? Vraag hoe een gewone werkdag eruitziet.'},
};
const ids=['s5-sources','s5-fit','s5-match','s5-reaction-example','s5-reaction'];
const educationSources=[['Opleidingswebsites','Zoek op onderwerp, plaats en niveau.'],['Bij een school','Bekijk het aanbod of vraag om uitleg.']] as const;
const educationPreferences=[['De inhoud past bij mij','Wat leer je en wat kun je er later mee doen?'],['De manier van leren past bij mij','Kijk of je vooral op school leert of leren en werken combineert.'],['De plek is bereikbaar','Kun je goed bij de opleiding komen?'],['De voorwaarden zijn duidelijk','Bekijk wat je nodig hebt om te kunnen beginnen.']] as const;
const Eye=()=> <svg className="eye-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/></svg>;
const Visibility=()=> <div className="visibility-note"><Eye/><span>Alleen jij en de begeleiders kunnen dit antwoord zien.</span></div>;
function Vacancy(){return <article className="vacancy-card"><span className="question-count">Voorbeeld van een baan</span><h2>Verkoopmedewerker kledingwinkel</h2><p>Kledingwinkel · Zeist · 24–32 uur</p><dl><div><dt>Wat ga je doen?</dt><dd>Klanten helpen, kleding netjes houden en achter de kassa werken.</dd></div><div><dt>Wat vragen ze?</dt><dd>Je bent vriendelijk, helpt graag mensen en vindt samenwerken prettig.</dd></div><div><dt>Het bedrijf</dt><dd>Een middelgrote winkel met een jong team en een informele sfeer.</dd></div></dl></article>}
function EducationSearchHelp(){return <>
 <p>Je kunt veel informatie vinden over verschillende soorten en niveaus van opleidingen op Leeroverzicht.nl.</p>
 <a className="education-search-link" href="https://www.leeroverzicht.nl/leren" target="_blank" rel="noopener noreferrer">Open Leeroverzicht.nl (opent in nieuw tabblad)</a>
 <p>Wil je mbo-opleidingen bekijken? Op KiesMBO kun je opleidingen en scholen vinden.</p>
 <a className="education-search-link" href="https://www.kiesmbo.nl/opleidingen" target="_blank" rel="noopener noreferrer">Open KiesMBO (opent in nieuw tabblad)</a>
 <div className="notice-box"><strong>Vraag de AI-assistent</strong><p>Bijvoorbeeld: “Welke opleidingen passen bij mijn interesses?”</p><span>Deze functie is binnenkort beschikbaar. Bespreek je ideeën alvast met je begeleider.</span></div>
 </>}

export function StepFiveFlow({repository,participantId,trajectoryCode,onClose}:{repository:AnswerRepository;participantId:string;trajectoryCode:string;onClose:()=>void}){
 const[stage,setStage]=useState<'intro'|'route'|'parts'|'guide'|'education'|'done'>('intro');const[index,setIndex]=useState(0);const[selected,setSelected]=useState<string[]>([]);const[chosenSources,setChosenSources]=useState<string[]>([]);const[match,setMatch]=useState('');const[reaction,setReaction]=useState('');const[notice,setNotice]=useState('');
 const[route,setRoute]=useState<'work'|'education'|'both'|'unsure'>('work');const[educationIndex,setEducationIndex]=useState(0);const[educationSelected,setEducationSelected]=useState<string[]>([]);const[educationInterest,setEducationInterest]=useState('');
 useEffect(()=>{repository.get(participantId,trajectoryCode,'s5-route').then(answer=>{const value=answer?.value;if(value==='work'||value==='education'||value==='both'||value==='unsure')setRoute(value)})},[participantId,repository,trajectoryCode]);
 useEffect(()=>{if(stage!=='parts')return;repository.get(participantId,trajectoryCode,ids[index]).then(answer=>{const stored=answer?.value;setSelected(index<2&&Array.isArray(stored)?stored:[]);if(index===2)setMatch(typeof stored==='string'?stored:'');if(index===4)setReaction(typeof stored==='string'?stored:'');setNotice(answer?'Automatisch opgeslagen':'')})},[index,participantId,repository,stage,trajectoryCode]);
 useEffect(()=>{if(stage!=='guide')return;repository.get(participantId,trajectoryCode,'s5-sources').then(answer=>setChosenSources(Array.isArray(answer?.value)?answer.value:[]))},[participantId,repository,stage,trajectoryCode]);
 useEffect(()=>{if(stage!=='education')return;const id=['s5-education-sources','s5-education-fit','s5-education-interest'][educationIndex];repository.get(participantId,trajectoryCode,id).then(answer=>{const stored=answer?.value;if(educationIndex<2)setEducationSelected(Array.isArray(stored)?stored:[]);else setEducationInterest(typeof stored==='string'?stored:'');setNotice(answer?'Automatisch opgeslagen':'')})},[educationIndex,participantId,repository,stage,trajectoryCode]);
 const saveEducation=async(value: string[]|string=educationIndex<2?educationSelected:educationInterest)=>{setNotice('Opslaan…');try{await repository.save({participantId,trajectoryCode,activityId:['s5-education-sources','s5-education-fit','s5-education-interest'][educationIndex],value,updatedAt:new Date().toISOString()});setNotice('Automatisch opgeslagen');return true}catch{setNotice('Opslaan is niet gelukt');return false}};
 const chooseEducation=(item:string)=>{const nextValues=educationSelected.includes(item)?educationSelected.filter(x=>x!==item):[...educationSelected,item];setEducationSelected(nextValues);void saveEducation(nextValues)};
 const educationChoices=(items:readonly(readonly[string,string])[])=> <div className="choice-list">{items.map(([title,description])=><button className={`choice-card ${educationSelected.includes(title)?'selected':''}`} key={title} onClick={()=>chooseEducation(title)}><span>{educationSelected.includes(title)?'✓':''}</span><div><strong>{title}</strong><p>{description}</p></div></button>)}</div>;
 const beginRoute=async()=>{try{await repository.save({participantId,trajectoryCode,activityId:'s5-route',value:route,updatedAt:new Date().toISOString()});setNotice('');setStage(route==='education'||route==='unsure'?'education':'parts')}catch{setNotice('Opslaan is niet gelukt')}};
 const nextEducation=async()=>{if(!await saveEducation())return;if(educationIndex===2)setStage(route==='unsure'?'parts':'done');else{setEducationIndex(i=>i+1);setEducationSelected([]);setNotice('')}};
 const value=()=>index<2?selected:index===2?match:index===4?reaction:'';
 const save=async(nextValue=value())=>{setNotice('Opslaan…');try{await repository.save({participantId,trajectoryCode,activityId:ids[index],value:nextValue,updatedAt:new Date().toISOString()});setNotice('Automatisch opgeslagen')}catch{setNotice('Opslaan is niet gelukt')}};
 const next=async()=>{await save();if(index===1){setStage('guide')}else if(index===4){setNotice('');setStage(route==='both'?'education':'done')}else{setIndex(i=>i+1);setSelected([]);setNotice('')}};
 const toggle=(item:string)=>{const nextValues=selected.includes(item)?selected.filter(x=>x!==item):[...selected,item];setSelected(nextValues);void save(nextValues)};
 const choices=(items:readonly(readonly[string,string])[])=> <div className="choice-list">{items.map(([title,text])=><button className={`choice-card ${selected.includes(title)?'selected':''}`} key={title} onClick={()=>toggle(title)}><span>{selected.includes(title)?'✓':''}</span><div><strong>{title}</strong><p>{text}</p></div></button>)}</div>;
 if(stage==='intro')return <section className="step-flow"><span className="eyebrow">Stap 5 · Werk en opleiding verkennen</span><h1>Ontdek wat bij jou past</h1><p>Je verkent hoe je werk of een opleiding kunt vinden. Je hoeft nog niet te solliciteren of je ergens aan te melden.</p><section className="flow-card"><h2>Dit ga je doen</h2><ol className="numbered-info"><li>Kiezen of je werk, een opleiding of allebei wilt onderzoeken.</li><li>Ontdekken waar je kunt zoeken en waar je op kunt letten.</li><li>Een voorbeeld bekijken of opschrijven wat je wilt onderzoeken.</li></ol></section><button className="flow-primary" onClick={()=>setStage('route')}>Begin met deze stap</button><button className="flow-secondary" onClick={onClose}>Terug naar mijn route</button></section>;
 if(stage==='route')return <section className="step-flow"><span className="eyebrow">Stap 5 · Jouw richting</span><h1>Wat wil je onderzoeken?</h1><p>Dit is nog geen definitieve keuze. In stap 7 bespreek je jouw mogelijkheden.</p><section className="flow-card"><div className="choice-list">{([['work','Werk'],['education','Een opleiding'],['both','Werk én opleiding'],['unsure','Ik weet het nog niet']] as const).map(([value,label])=><button className={`choice-card ${route===value?'selected':''}`} key={value} onClick={()=>setRoute(value)}><span>{route===value?'✓':''}</span><div><strong>{label}</strong></div></button>)}</div>{notice&&<div className="save-state">{notice}</div>}<Visibility/></section><button className="flow-primary" onClick={()=>void beginRoute()}>Verder</button><button className="flow-secondary" onClick={()=>setStage('intro')}>Terug naar uitleg</button></section>;
 if(stage==='education'){const educationScreens=[<><h2>Waar kun je een opleiding vinden?</h2><p>Kies hoe jij zou willen zoeken.</p>{educationChoices(educationSources)}<EducationSearchHelp/><Visibility/></>,<><h2>Wat past bij jou?</h2><p>Waar wil jij op letten bij een opleiding?</p>{educationChoices(educationPreferences)}<Visibility/></>,<><h2>Welke opleiding wil je onderzoeken?</h2><p>Schrijf een opleiding of onderwerp op dat je aanspreekt. Weet je het nog niet? Schrijf dan op wat je graag zou willen leren.</p><textarea value={educationInterest} onChange={event=>setEducationInterest(event.target.value)} placeholder="Bijvoorbeeld: ik wil iets met techniek leren"/><p>Je kunt met je begeleider bespreken waar je deze opleiding vindt, wat je leert en wat je nodig hebt om te beginnen.</p><Visibility/></>];return <section className="step-flow"><span className="eyebrow">Stap 5 · Opleiding · {educationIndex+1} van 3</span><section className="flow-card question-card">{educationScreens[educationIndex]}{notice&&<div className="save-state">{notice}</div>}</section><button className="flow-primary" onClick={()=>void nextEducation()}>{educationIndex===2?(route==='unsure'?'Bekijk ook werk':'Rond deze stap af'):'Volgende'}</button><button className="flow-secondary" onClick={()=>educationIndex===0?setStage(route==='both'?'parts':'route'):setEducationIndex(i=>i-1)}>{educationIndex===0?'Vorige':'Vorige vraag'}</button></section>}
 if(stage==='guide')return <section className="step-flow"><span className="eyebrow">Stap 5 · Jouw keuzes</span><h1>Wat past bij jou?</h1><p>Hieronder lees je meer over de onderwerpen die je hebt gekozen. Je hoeft nog niet op een baan te reageren.</p><section className="flow-card choice-guidance">{chosenSources.length>0&&<><h2>Zo kun je werk vinden</h2>{chosenSources.map(title=><article className="guidance-item" key={title}><h3>{title}</h3><p>{guidance[title]?.explanation}</p><p className="guidance-example">{guidance[title]?.example}</p>{guidance[title]?.url&&<a href={guidance[title].url} target="_blank" rel="noopener noreferrer">{guidance[title].linkLabel} (opent in nieuw tabblad)</a>}{title==='Websites met banen'&&<><p>Op de website Werk.nl van het UWV vind je naast vacatures ook veel aanvullende informatie met betrekking tot werk.</p><a href="https://www.werk.nl/werkzoekenden/" target="_blank" rel="noopener noreferrer">Open Werk.nl (opent in nieuw tabblad)</a></>}</article>)}</>}{selected.length>0&&<><h2>Hier wil jij op letten</h2>{selected.map(title=><article className="guidance-item" key={title}><h3>{title}</h3><p>{guidance[title]?.explanation}</p><p className="guidance-example">{guidance[title]?.example}</p></article>)}</>}{chosenSources.length===0&&selected.length===0&&<p>Je hebt nog niets gekozen. Ga terug en vink aan wat jou aanspreekt.</p>}<Visibility/></section><button className="flow-primary" onClick={()=>{setIndex(2);setSelected([]);setNotice('');setStage('parts')}}>Bekijk een voorbeeldbaan</button><button className="flow-secondary" onClick={()=>setStage('parts')}>Terug naar mijn keuzes</button></section>;
 if(stage==='done')return <section className="step-flow"><span className="eyebrow">Stap 5 · Klaar</span><h1>Je hebt jouw mogelijkheden verkend</h1><p>Je weet beter waar je werk of een opleiding kunt zoeken en waar je op kunt letten.</p><section className="flow-card"><h2>Mooi gedaan</h2><p>Bespreek met je begeleider wat je hebt gevonden en wat je verder wilt onderzoeken.</p><Visibility/></section><button className="flow-primary orange" onClick={onClose}>Terug naar mijn route</button></section>;
 const screens=[<><h2>Waar kun je werk vinden?</h2><p>Kies wat jij zou willen proberen.</p>{choices(sources)}<Visibility/></>,<><h2>Wat past bij jou?</h2><p>Waar wil jij op letten als je naar werk kijkt?</p>{choices(preferences)}<Visibility/></>,<><h2>Een baan bekijken en kijken of deze bij mij past</h2><p>Lees rustig wat het werk inhoudt en wat het bedrijf zoekt. Denk aan het werk én aan het bedrijf.</p><Vacancy/><label className="field-label">Wat denk jij?<select value={match} onChange={e=>setMatch(e.target.value)}><option value="">Kies een antwoord</option><option>Ja</option><option>Misschien</option><option>Nee</option></select></label><Visibility/></>,<><h2>Hoe kun je reageren?</h2><p>Een reactie mag kort, duidelijk en persoonlijk zijn.</p><div className="reaction-example"><p>Hoi, de baan als verkoopmedewerker in jullie kledingwinkel lijkt mij heel leuk en past denk ik goed bij mij. Ik help graag mensen en zou graag kennismaken.</p><p>Groet,<br/>Sam</p></div></>,<><h2>Jouw reactie voorbereiden</h2><p>Schrijf hoe jij op deze baan zou kunnen reageren.</p><textarea value={reaction} onChange={e=>setReaction(e.target.value)} placeholder="Schrijf hier jouw reactie…"/><Visibility/><button className="flow-secondary" onClick={()=>setNotice('De AI-assistent wordt later aan deze reactie gekoppeld.')}>Vraag de AI-assistent</button></>];
 return <section className="step-flow"><span className="eyebrow">Stap 5 · Werk · {index+1} van 5</span><section className="flow-card question-card">{screens[index]}{notice&&<div className="save-state">{notice}</div>}</section><button className="flow-primary" onClick={()=>void next()}>{index===4?(route==='both'?'Bekijk ook opleidingen':'Rond deze stap af'):'Volgende'}</button><button className="flow-secondary" onClick={()=>index===0?setStage(route==='unsure'?'education':'route'):index===2?setStage('guide'):setIndex(i=>i-1)}>{index===0?'Terug naar keuze':'Vorige'}</button></section>;
}
