import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import type { DashboardRepository, DashboardTrajectory, ManagedRole, ManagedUser } from './domain';
const labels:Record<ManagedRole,string>={project_leader:'Applicatiebeheerder',coach:'Begeleider',commissioner:'Opdrachtgever'};
export function UsersRoles({trajectories,repository}:{trajectories:DashboardTrajectory[];repository:DashboardRepository}){
 const[users,setUsers]=useState<ManagedUser[]>([]),[organizations,setOrganizations]=useState<Array<{code:string;name:string;active:boolean}>>([]),[editing,setEditing]=useState<ManagedUser>(),[creating,setCreating]=useState(false),[role,setRole]=useState<ManagedRole>('coach'),[assignedOrganization,setAssignedOrganization]=useState('Munks BV'),[showInactive,setShowInactive]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>repository.listManagementOptions().then(o=>{setUsers(o.users??[]);setOrganizations(o.organizations??[])}).catch(e=>setMessage(e instanceof Error?e.message:'Gebruikers laden is mislukt.'));useEffect(()=>{void load()},[repository]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const d=new FormData(e.currentTarget),trajectoryCodes=d.getAll('trajectories').map(String);if(role!=='project_leader'&&!trajectoryCodes.length){setMessage(role==='coach'?'Kies minimaal één traject voor deze begeleider.':'Kies minimaal één traject voor deze opdrachtgever.');return}const user:ManagedUser={id:editing?.id??'',name:String(d.get('name')??'').trim(),email:String(d.get('email')??'').trim(),role,organization:String(d.get('organization')??'').trim(),commissionerCode:role==='commissioner'?String(d.get('commissionerCode')??'').trim().toUpperCase():undefined,trajectoryCodes,active:d.get('active')==='on'};setBusy(true);try{await repository.saveManagedUser(user);await load();setEditing(undefined);setCreating(false);setMessage(editing?'De gebruiker is bijgewerkt.':'De uitnodigingsmail is verstuurd.')}catch(error){setMessage(error instanceof Error?error.message:'Opslaan is mislukt.')}finally{setBusy(false)}};
 if(creating||editing){const availableOrganizations=organizations.filter(o=>o.active||o.name===editing?.organization);const commissionerCode=availableOrganizations.find(o=>o.name===assignedOrganization)?.code??'';const visibleTrajectories=role==='commissioner'?trajectories.filter(t=>t.commissionerName===assignedOrganization):trajectories;return <section className="admin-form user-form"><h2>{editing?'Gebruiker wijzigen':'Nieuwe gebruiker uitnodigen'}</h2>{message&&<p className="dashboard-message">{message}</p>}<form onSubmit={save}><label>Naam<input name="name" required defaultValue={editing?.name}/></label><label>E-mailadres<input name="email" type="email" required defaultValue={editing?.email}/></label><label>Rol<select value={role} onChange={e=>{const next=e.target.value as ManagedRole;setRole(next);if(next==='commissioner'&&assignedOrganization==='Munks BV')setAssignedOrganization(availableOrganizations[0]?.name??'')}}><option value="project_leader">Applicatiebeheerder</option><option value="coach">Begeleider</option><option value="commissioner">Opdrachtgever</option></select></label><label>Organisatie<select name="organization" required value={assignedOrganization} onChange={e=>setAssignedOrganization(e.target.value)}>{role!=='commissioner'&&<option value="Munks BV">Munks BV</option>}{availableOrganizations.filter(o=>o.name!=='Munks BV').map(o=><option value={o.name} key={o.code}>{o.name}</option>)}</select></label>{role==='commissioner'&&<label>Opdrachtgevercode<input name="commissionerCode" required value={commissionerCode} readOnly aria-readonly="true"/></label>}{role==='project_leader'?<p className="notice-box">Een applicatiebeheerder heeft automatisch toegang tot het algemene beheer en alle trajecten.</p>:<fieldset className="coach-selection"><legend>Toegang tot trajecten</legend>{visibleTrajectories.length?visibleTrajectories.map(t=><label className="check" key={t.code}><input type="checkbox" name="trajectories" value={t.code} defaultChecked={editing?.trajectoryCodes.includes(t.code)}/><span>{t.name} · {t.code}</span></label>):<p>Voor deze organisatie zijn nog geen trajecten beschikbaar.</p>}</fieldset>}<label className="check"><input type="checkbox" name="active" defaultChecked={editing?.active??true}/><span>Account actief</span></label><div><button className="release-button" disabled={busy}>{busy?(editing?'Opslaan…':'Uitnodiging versturen…'):'Opslaan'}</button><button type="button" className="close-button" disabled={busy} onClick={()=>{setCreating(false);setEditing(undefined)}}>Annuleren</button></div></form></section>}
 return <section className="users-panel"><header><div><h2>Gebruikers en rollen</h2><p>Beheer medewerkers, opdrachtgevers en toegang tot trajecten.</p></div><button onClick={()=>{setEditing(undefined);setRole('coach');setAssignedOrganization('Munks BV');setCreating(true);setMessage('')}}>Nieuwe gebruiker uitnodigen</button></header>{message&&<p className="dashboard-message">{message}</p>}<label className="check"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/><span>Toon ook niet-actieve gebruikers</span></label><div className="users-list">{users.filter(u=>showInactive||u.active).map(u=><article key={u.id}><div><strong>{u.name}</strong><span>{u.email}</span><small>{u.organization}</small></div><div><strong>{labels[u.role]}</strong><span>{u.trajectoryCodes.length?u.trajectoryCodes.join(', '):'Alleen algemeen beheer'}</span><small>{u.active?'Actief':'Inactief'}</small></div><button onClick={()=>{setEditing(u);setRole(u.role);setAssignedOrganization(u.organization);setCreating(false);setMessage('')}}>Wijzigen</button></article>)}</div></section>;
}
